"""
Grant Seeker — daily digest email composer / sender (proof of concept).

Reads recipients.yaml, opens each email with that person's greeting and a
fresh, (allegedly) hilarious joke about flood modelling generated by Claude,
then appends the digest of funding opportunities.

Use --dry-run to PRINT the emails instead of sending them — handy for testing
before any mail server is configured.

Run:
    python email_digest.py --opps out.json --dry-run     # preview (no sending)
    python email_digest.py --opps out.json               # send (needs SMTP_* env vars)

`out.json` is produced by:  python scout.py --json out.json
"""

import argparse
import json
import os
import smtplib
import sys
import urllib.error
import urllib.request
from email.message import EmailMessage

import anthropic
import yaml

# Same fallback chain as scout.py: Opus first, Sonnet if Opus is overloaded.
MODELS = ["claude-opus-4-8", "claude-sonnet-4-6"]

# Flavor text for the email intro. Just the name shown to readers — change
# freely (the actual model used may be Opus or Sonnet depending on fallback).
ASSISTANT_NAME = "Claude Sonnet"

# Background blurb shown in every email, after the joke and before the digest.
INTRO = (
    f"Your colleague Maarten asked his AI buddy {ASSISTANT_NAME} to scour the "
    "web for interesting funding leads for FloodAdapt. This is now done "
    "automatically every day through GitHub Actions.\n"
    "\n"
    "How it works: every morning a scheduled job turns Claude loose on the web "
    "to hunt for grants, RFPs, and RFIs across coastal & inland flooding, flood "
    "resilience, and flood risk mapping. It pulls out the bits that matter — "
    "deadline, eligibility, budget, and a one-paragraph summary — checks them "
    "against everything it has already seen so you only get fresh leads, and "
    "then emails you the new ones plus a running top-10. No spreadsheets were "
    "harmed (and barely any humans were involved) in the making of this digest.\n"
    "\n"
    "You cannot opt out of this email chain — unless you ask Maarten nicely."
)


def load_recipients(path: str) -> list:
    with open(path, encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    recipients = data.get("recipients", [])
    if not recipients:
        raise SystemExit(f"No recipients found in {path}.")
    for r in recipients:
        if "email" not in r or "greeting" not in r:
            raise SystemExit(f"Each recipient needs 'email' and 'greeting': {r}")
    return recipients


def make_joke(client: anthropic.Anthropic) -> str:
    """Generate one short, fresh joke about flood modelling."""
    prompt = (
        "Write ONE short, genuinely funny joke about flood modelling / "
        "hydrodynamic flood simulation. Fair game: SFINCS, bathymetry, "
        "boundary conditions, calibration, Manning's n, grid resolution, "
        "wet/dry cells, 'it's just water'. One or two lines, clever, "
        "office-appropriate. Return ONLY the joke text, no preamble."
    )
    for i, model in enumerate(MODELS):
        try:
            resp = client.messages.create(
                model=model,
                max_tokens=300,
                messages=[{"role": "user", "content": prompt}],
            )
        except anthropic.APIStatusError as e:
            if (e.status_code == 429 or e.status_code >= 500) and i < len(MODELS) - 1:
                continue
            raise
        return "".join(b.text for b in resp.content if b.type == "text").strip()
    return ""


def build_digest_body(opps_path: str | None) -> str:
    if not opps_path or not os.path.exists(opps_path):
        return (
            "(No opportunities file found yet. Run `python scout.py --json out.json` "
            "first, then pass --opps out.json here.)"
        )
    with open(opps_path, encoding="utf-8") as f:
        data = json.load(f)
    opps = data.get("opportunities", [])
    if not opps:
        return "No funding opportunities to report today."

    lines = ["Here are the latest flood-related funding opportunities:", ""]
    for i, o in enumerate(opps, 1):
        lines.append(f"{i}. {o.get('title', '?')} — {o.get('funder', '?')}")
        lines.append(f"   {o.get('one_liner', '')}")
        lines.append(f"   Due: {o.get('due_date', '?')}  |  Budget: {o.get('budget', '?')}")
        lines.append(f"   Eligibility: {o.get('eligibility', '?')}")
        lines.append(f"   {o.get('source_url', '')}")
        lines.append("")
    return "\n".join(lines)


def compose(greeting: str, joke: str, body: str) -> str:
    return "\n".join([greeting, "", joke, "", INTRO, "", body, "", "— Grant Seeker"])


def _send_via_resend(to_addr: str, subject: str, body: str, api_key: str, sender: str) -> None:
    """Send over HTTPS via the Resend API (works from corporate nets / CI)."""
    payload = json.dumps(
        {"from": sender, "to": [to_addr], "subject": subject, "text": body}
    ).encode("utf-8")
    req = urllib.request.Request(
        "https://api.resend.com/emails",
        data=payload,
        method="POST",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            # Resend's API is behind Cloudflare, which 403s (code 1010) the
            # default Python-urllib User-Agent as a bot. Send a normal one.
            "User-Agent": "Mozilla/5.0 (compatible; GrantSeeker/1.0)",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            resp.read()
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", "replace")
        raise RuntimeError(f"Resend error {e.code}: {detail}")
    print(f"Sent to {to_addr} (via Resend)")


def send_email(
    to_addr: str, subject: str, body: str, *, dry_run: bool, prefer_smtp: bool = False
) -> None:
    if dry_run:
        print("=" * 70)
        print(f"To: {to_addr}")
        print(f"Subject: {subject}\n")
        print(body)
        print("=" * 70 + "\n")
        return

    # Preferred: Resend over HTTPS (port 443) — not blocked by corporate
    # firewalls or GitHub Actions, unlike SMTP. Use --smtp to force SMTP
    # (e.g. to send from your own Deltares/Office365 address).
    resend_key = os.environ.get("RESEND_API_KEY")
    if resend_key and not prefer_smtp:
        sender = os.environ.get("EMAIL_FROM", "onboarding@resend.dev")
        _send_via_resend(to_addr, subject, body, resend_key, sender)
        return

    # Fallback: SMTP (often blocked on corporate networks — see the SSL error).
    host = os.environ.get("SMTP_HOST")
    port = int(os.environ.get("SMTP_PORT", "587"))
    user = os.environ.get("SMTP_USER")
    password = os.environ.get("SMTP_PASS")
    sender = os.environ.get("EMAIL_FROM", user)
    if not (host and user and password):
        raise SystemExit(
            "No sender configured. Set RESEND_API_KEY (recommended), or "
            "SMTP_HOST/SMTP_USER/SMTP_PASS — or use --dry-run to preview."
        )

    msg = EmailMessage()
    msg["From"] = sender
    msg["To"] = to_addr
    msg["Subject"] = subject
    msg.set_content(body)

    with smtplib.SMTP(host, port) as server:
        server.starttls()
        server.login(user, password)
        server.send_message(msg)
    print(f"Sent to {to_addr}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--opps", help="path to opportunities JSON (from scout.py --json)")
    ap.add_argument("--recipients", default="recipients.yaml")
    ap.add_argument("--subject", default="Flood funding — daily digest")
    ap.add_argument("--dry-run", action="store_true", help="print emails instead of sending")
    ap.add_argument(
        "--smtp",
        action="store_true",
        help="force SMTP even if RESEND_API_KEY is set (e.g. send from your own address)",
    )
    args = ap.parse_args()

    if not os.environ.get("ANTHROPIC_API_KEY"):
        raise SystemExit("Set ANTHROPIC_API_KEY first.")

    recipients = load_recipients(args.recipients)
    client = anthropic.Anthropic(max_retries=6)
    body_core = build_digest_body(args.opps)

    # A fresh joke per recipient, so every email opens differently.
    # One bad recipient (e.g. blocked by Resend until a domain is verified)
    # shouldn't stop the others.
    failures = 0
    for r in recipients:
        joke = make_joke(client)
        body = compose(r["greeting"], joke, body_core)
        try:
            send_email(
                r["email"], args.subject, body, dry_run=args.dry_run, prefer_smtp=args.smtp
            )
        except Exception as e:  # noqa: BLE001 - report and continue per recipient
            failures += 1
            print(f"Failed to send to {r['email']}: {e}", file=sys.stderr)
    if failures:
        raise SystemExit(f"{failures} of {len(recipients)} email(s) failed.")


if __name__ == "__main__":
    main()
